version: "3"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - 13307:3306
    networks:
      - dtm-net
    volumes:
      - /etc/localtime:/etc/localtime
      - ./scripts:/docker-entrypoint-initdb.d

networks:
  dtm-net:
    driver: bridge